apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-deployment
spec:
  selector:
    matchLabels:
      app: movie-app
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app-container
        image: ajumanoh/movie-search-app:latest
        imagePullPolicy: IfNotPresent
#       command: ["npm run migrate"]
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-app-service
spec:
  selector:
    app: movie-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30759
  type: NodePort